Description: >
    Benny Server Stack with one WebServer in the Private Subnet 

Parameters:
  EnvironmentName: 
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  #IAM Role to allow EC2 Session Manager to access your server
  RoleForSSMAccess:
    Type: "AWS::IAM::Role"
    Properties:
      Description: "New IAM role to allow EC2 Session manager to Access the Ec2 WebServer"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  #Instance Profile
  ServerInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles: 
      - !Ref RoleForSSMAccess
  # Security Group for the Web Server
  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
  # WebServer EC2 Instance
  WebServerInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install apache2 -y
          sudo systemctl start apache2.service          
      ImageId: ami-005bdb005fb00e791
      IamInstanceProfile: !Ref ServerInstanceProfile
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - Ref: "WebAccessSecurityGroup"
          SubnetId: 
            Fn::ImportValue:
              !Sub "${EnvironmentName}-PRI-SN"